// This file was automatically generated by protocompiler
// DO NOT EDIT!
// Compiled from stdin

#include <stdint.h>
#ifdef __OBJC__
#include <Foundation/Foundation.h>
#endif

#ifndef NS_ENUM
#if (__cplusplus && __cplusplus >= 201103L && (__has_extension(cxx_strong_enums) || __has_feature(objc_fixed_enum))) || (!__cplusplus && __has_feature(objc_fixed_enum))
#define NS_ENUM(_type, _name) enum _name : _type _name; enum _name : _type
#else
#define NS_ENUM(_type, _name) _type _name; enum
#endif
#endif // !defined(NS_ENUM)

typedef NS_ENUM(int32_t, AWDIPConfigurationInterfaceType) {
    AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_OTHER = 0,
    AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_WIFI = 1,
    AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_CELLULAR = 2,
    AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_WIRED = 3,
};
#ifdef __OBJC__
NS_INLINE NSString *AWDIPConfigurationInterfaceTypeAsString(AWDIPConfigurationInterfaceType value)
{
    switch (value)
    {
        case AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_OTHER: return @"IPCONFIGURATION_INTERFACE_TYPE_OTHER";
        case AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_WIFI: return @"IPCONFIGURATION_INTERFACE_TYPE_WIFI";
        case AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_CELLULAR: return @"IPCONFIGURATION_INTERFACE_TYPE_CELLULAR";
        case AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_WIRED: return @"IPCONFIGURATION_INTERFACE_TYPE_WIRED";
        default: return [NSString stringWithFormat:@"(unknown: %i)", value];
    }
}
#endif /* __OBJC__ */
#ifdef __OBJC__
NS_INLINE AWDIPConfigurationInterfaceType StringAsAWDIPConfigurationInterfaceType(NSString *value)
{
    if ([value isEqualToString:@"IPCONFIGURATION_INTERFACE_TYPE_OTHER"]) return AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_OTHER;
    if ([value isEqualToString:@"IPCONFIGURATION_INTERFACE_TYPE_WIFI"]) return AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_WIFI;
    if ([value isEqualToString:@"IPCONFIGURATION_INTERFACE_TYPE_CELLULAR"]) return AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_CELLULAR;
    if ([value isEqualToString:@"IPCONFIGURATION_INTERFACE_TYPE_WIRED"]) return AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_WIRED;
    return AWDIPConfigurationInterfaceType_IPCONFIGURATION_INTERFACE_TYPE_OTHER;
}
#endif /* __OBJC__ */
