######################################################################
#BEGIN	Machine dependent Makefile fragment for riscv64
######################################################################

$(foreach file,$(OBJS),$(eval $(file)_CFLAGS_ADD += $(CFLAGS_NOLTO_FLAG)))

######################################################################
#END	Machine dependent Makefile fragment for riscv64
######################################################################
