#ifndef _PUREDARWIN_SYSTEM_LIBKERN_OSSERIALIZEBINARY_H_
#define _PUREDARWIN_SYSTEM_LIBKERN_OSSERIALIZEBINARY_H_

#include <libkern/OSSerializeBinary.h>

#endif /* _PUREDARWIN_SYSTEM_LIBKERN_OSSERIALIZEBINARY_H_ */
