{ stdenv
, lib
, perl
, python3
, buildPackages
, darwinCrossToolchain
, nativeLd
, libSystem
, libcss
, libwapcaplet
, libparserutils
, targetTriple ? "x86_64-apple-darwin20.4"
, appleSdk
}:

let
  deps = [ libwapcaplet libparserutils ];
in
stdenv.mkDerivation {
  pname = "puredarwin-libcss";
  inherit (libcss) version src;

  nativeBuildInputs = [ perl python3 buildPackages.stdenv.cc ];

  buildPhase = ''
    runHook preBuild

    mkdir -p sdk
    export DARWIN_SDK_ROOT="${appleSdk}/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"

    python3 src/select/select_generator.py

    BUILD_CC="$CC_FOR_BUILD"
    if [ -z "$BUILD_CC" ]; then BUILD_CC=cc; fi
    "$BUILD_CC" -o gen_parser src/parse/properties/css_property_parser_gen.c

    props=$(perl -pe'$_="" unless /^([^\#][^:]+):/;$_=$1 . " "' src/parse/properties/properties.gen)
    for prop in $props; do
      line=$(grep "^$prop:" src/parse/properties/properties.gen)
      ./gen_parser -o "src/parse/properties/autogenerated_$prop.c" "$line"
    done

    CC="${darwinCrossToolchain}/bin/${targetTriple}-clang"

    CFLAGS="-isysroot $DARWIN_SDK_ROOT -mmacosx-version-min=26.5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -fno-stack-protector -D_ALIGNED=__attribute__((aligned)) -DSTMTEXPR=1 -Iinclude -Isrc -I${libSystem}/usr/include ${lib.concatMapStringsSep " " (dep: "-I${dep}/include") deps}"

    srcs=$(find src -name '*.c' -not -name css_property_parser_gen.c)
    for f in $srcs; do
      obj=$(echo "$f" | tr '/' '_').o
      "$CC" $CFLAGS -c "$f" -o "$obj"
    done

    "$CC" -dynamiclib \
      -isysroot "$DARWIN_SDK_ROOT" -mmacosx-version-min=26.5 \
      -fuse-ld=${nativeLd}/bin/ld \
      -nostdlib \
      -L${libSystem}/usr/lib ${lib.concatMapStringsSep " " (dep: "-L${dep}/lib") deps} \
      -Wl,-dylib_file,/usr/lib/system/libdyld.dylib:${libSystem}/usr/lib/system/libdyld.dylib \
      -Wl,-platform_version,macos,26.5,26.5 \
      -install_name /lib/libcss.dylib \
      -lwapcaplet -lparserutils -lSystem \
      *.o \
      -o libcss.dylib

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p "$out/lib/pkgconfig" "$out/include"
    install -m755 libcss.dylib "$out/lib/libcss.dylib"
    cp -r include/libcss "$out/include/libcss"

    cat > "$out/lib/pkgconfig/libcss.pc" <<EOF
prefix=$out
libdir=\''${prefix}/lib
includedir=\''${prefix}/include

Name: libcss
Description: CSS parsing and selection library for NetSurf
Version: ${libcss.version}
Requires: libparserutils libwapcaplet
Libs: -L\''${libdir} -lcss
Cflags: -I\''${includedir}
EOF

    runHook postInstall
  '';

  dontFixup = true;

  meta = with lib; {
    description = "libcss (NetSurf CSS parsing/selection library), cross-built for PureDarwin";
    platforms = platforms.linux;
  };
}
