######################################################################
#BEGIN	Machine dependent Makefile fragment for riscv64
######################################################################

CWARNFLAGS = $(CWARNFLAGS_STD) -Wshorten-64-to-32

lz4.o_CFLAGS_ADD += -fbuiltin -O3

######################################################################
#END	Machine dependent Makefile fragment for riscv64
######################################################################
