#!/usr/bin/env bash
# regenerates the libc++ and libc++abi export lists from the built dylibs of every arch
# run from the PureDarwin root, pass extra nix flags (e.g. --override-input) as arguments
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
nm=$(nix build --no-link --print-out-paths "$@" .#riscv64-cross-toolchain)/bin/riscv64-apple-darwin20.4-nm
declare -A abi cxx
abi[x86_64]=.#libcxxabi-dylib; cxx[x86_64]=.#libcxx-dylib
abi[arm64]=.#libcxxabiDylib-arm64; cxx[arm64]=.#libcxxDylib-arm64
abi[riscv64]=.#libcxxabi-dylib-riscv64; cxx[riscv64]=.#libcxx-dylib-riscv64
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
syms() {
  # temporary: riscv global merge exports __MergedGlobals_* until the toolchain stops it
  "$nm" -gU "$1" | awk '{print $3}' | grep -v '^__MergedGlobals' | sort -u
}
for a in x86_64 arm64 riscv64; do
  syms "$(nix build --no-link --print-out-paths "$@" "${abi[$a]}")/usr/lib/libc++abi.dylib" > "$tmp/abi.$a"
  syms "$(nix build --no-link --print-out-paths "$@" "${cxx[$a]}")/usr/lib/libc++.1.dylib" > "$tmp/cxx.$a"
done
for a in arm64 riscv64; do
  if [ -n "$(comm -3 "$tmp/abi.$a" "$tmp/abi.x86_64")" ]; then
    echo "libc++abi exports differ on $a, the sdk tbd assumes one list" >&2
    exit 1
  fi
done
hdr='# generated by update.sh from the built dylib, one exported symbol per line, for the sdk tbd'
{ echo "$hdr"; comm -12 "$tmp/abi.x86_64" "$tmp/abi.arm64" | comm -12 - "$tmp/abi.riscv64"; } > "$here/libc++abi.exports"
comm -12 "$tmp/cxx.x86_64" "$tmp/cxx.arm64" | comm -12 - "$tmp/cxx.riscv64" > "$tmp/common"
{ echo "$hdr"; cat "$tmp/common"; } > "$here/libc++.exports"
for a in x86_64 arm64 riscv64; do
  { echo "$hdr"; comm -23 "$tmp/cxx.$a" "$tmp/common"; } > "$here/libc++.$a.exports"
done
