INCLUDED_TEST_SOURCE_DIRS += vm_stress_tests

vm_stress_tests/vm_stress: OTHER_CXXFLAGS += -std=c++20
vm_stress_tests/vm_stress: OTHER_LDFLAGS += -ldarwintest_utils
vm_stress_tests/vm_stress: INVALID_ARCHS = x86_64h

