set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "")

set(LIBUNWIND_STANDALONE_BUILD ON CACHE BOOL "")
set(LIBUNWIND_APPLE_SYSTEM_BUILD ON CACHE BOOL "")
set(LIBUNWIND_APPLE_PLATFORM "osx" CACHE STRING "")

set(CMAKE_C_FLAGS_RELWITHDEBINFO "-Os -g" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-Os -g" CACHE STRING "")
set(LIBUNWIND_ENABLE_ASSERTIONS OFF CACHE BOOL "")
set(LIBUNWIND_ENABLE_CROSS_UNWINDING ON CACHE BOOL "")
set(LIBUNWIND_VERSION "1.0" CACHE STRING "")
