include(${CMAKE_CURRENT_LIST_DIR}/Apple.cmake)

set(CMAKE_INSTALL_NAME_DIR "/usr/local/lib/dyld" CACHE STRING "")
set(LIBUNWIND_ENABLE_STATIC ON CACHE BOOL "")
set(LIBUNWIND_ENABLE_SHARED OFF CACHE BOOL "")
