include(${CMAKE_CURRENT_LIST_DIR}/Apple.cmake)

set(CMAKE_INSTALL_NAME_DIR "/usr/lib/system" CACHE STRING "")
set(CMAKE_BUILD_WITH_INSTALL_NAME_DIR ON CACHE BOOL "")
set(LIBUNWIND_ENABLE_STATIC OFF CACHE BOOL "")
set(LIBUNWIND_ENABLE_SHARED ON CACHE BOOL "")
