#ifndef PUREDARWIN_DYLD_COMPAT_SYS_KDEBUG_PRIVATE_H
#define PUREDARWIN_DYLD_COMPAT_SYS_KDEBUG_PRIVATE_H

#include "../../../../Kernel/xnu/bsd/sys/kdebug_private.h"

#endif /* PUREDARWIN_DYLD_COMPAT_SYS_KDEBUG_PRIVATE_H */
