
# Specific to PureDarwin compilation environment (e.g., for building MacPorts)
export CFLAGS=-I/opt/local/include
export LDFLAGS=-L/usr/local/lib
TCLSH=/opt/local/bin/tclsh

# Additional path for binary coming from MacPorts 
export PATH="/opt/local/bin:/opt/local/sbin:/usr/X11R6/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/libexec:/System/Library/CoreServices"
export MANPATH="/opt/local/man:/opt/local/share/man/:/usr/share/man:/usr/local/man:$MANPATH"

# Default editor
export EDITOR=/usr/bin/vi

# Related to X
export PATH="/usr/X11R6/bin:/usr/local/sbin:$PATH"
export DISPLAY=:0.0

# Cliché
alias GREP="grep --mmap --color=always"
alias ls='ls -G'
alias ll='ls -lh'

# Colored tty
TERM='xterm-color'

# Prompt
PS1='%n@%m:%~%# '

# Enable ctrl+A ctrl+E ctrl+D.. shortcuts
bindkey -e
