/*
 * PureDarwin: real notify_probes.h is auto-generated by `dtrace -h` from
 * notify_probes.d at build time - this tree has no real DTrace userland
 * probe-compilation support. Real DTrace's own generated header already
 * defines these NOTIFY_*_ENABLED()/NOTIFY_*() macros as cheap no-ops
 * (an `is-enabled` check that's false, and an empty probe call) whenever
 * the provider isn't actually active/traced - the same real fallback
 * behavior every untraced process on real macOS gets, not a fabrication.
 */
#ifndef PD_NOTIFY_PROBES_H
#define PD_NOTIFY_PROBES_H

#define NOTIFY_REGISTER_MACH_PORT_ENABLED() 0
#define NOTIFY_REGISTER_MACH_PORT(name, notify_port, flags, token) do { } while (0)

#define NOTIFY_POST_ENABLED() 0
#define NOTIFY_POST(name) do { } while (0)

#define NOTIFY_CHECK_ENABLED() 0
#define NOTIFY_CHECK(token, check) do { } while (0)

#define NOTIFY_DELIVER_START_ENABLED() 0
#define NOTIFY_DELIVER_START(name) do { } while (0)

#define NOTIFY_DELIVER_END_ENABLED() 0
#define NOTIFY_DELIVER_END(name) do { } while (0)

#endif /* PD_NOTIFY_PROBES_H */
