#!/bin/sh
#
# Hexley DarwinOS Mascot Copyright 2000 by Jon Hooper. All Rights Reserved.
# Copyright (c) 2007-2008 The PureDarwin Project.
# All rights reserved.
#
# @LICENSE_HEADER_START@
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# @LICENSE_HEADER_END@
#

#
# aladin <aladin@puredarwin.org>
#

#
# This (totally useless) script displays an ascii-art of Hexley against worm (for future easteregg) 
#

# 
# Changelog
#
# 20081209 - License header update - aladin
# 20080305 - Initial release - aladin
#


echo '                                                                                
                                                                                
                                         7II                                    
                                 7IIIIIII8II                                    
                                8IIZII8IIII$III78                               
                                8IIIIIII78IIIIIIIII8                            
                                III77Z77777ZIIZIIIIII                           
                                 IMM777777777IIZIIIIII.                         
                                 : O77777777Z7IIIIIIIII                         
                                M  77778==M7778IOIIIIII8                        
                         MZ ?777MM777M     8778IIIIIIIII             :.         
                         O$$777777778      Z87IIIIIIIIIIIIIZ     OIII8    O8    
                          O$$$$$$$M7    OMI778IIIIIZIIIIIII    7II8I    III     
                            $$$$$$$8,   MM77$IIIIIIZIIIII$  ,III      IIIII     
                            :$$$$$$$8MMMM777IIIIIIIIII8I   ZII~       IIIO  87  
             ~,,:           87$$$$$$$$$$7778IIIIIIIIII     III      ,II    III  
          ,,,====:,        O77$?O$$$$$$$$M7IIIIIIIIIZ:    ~II      ZII    8III  
        ,,=,=======:,    7777$????Z~?$$$M78IIIIII88        II8    ZIO      I7   
       ~:==,====,====,  87778O$???ZZI:77M IIII             8II8  II8      8I    
       ,==~:Z==,======,   7:   OM::::77O:8III$              ZIIIII8      8I8    
      ,~===I7O,========,    $77::::::7777OIIII                IIII$     III     
      ,======7MZ=======~777777::::::77777IIIII               III8IIIIIIII8      
      ,=======77========,777$:::::::777778IIII8             IIO    8III8        
      ,======== ,,,,,,,,,777::::::::7777777777.           :II8                  
     :~,======:  =======,77:::::::::77777777777M         ZII                    
     ,:==,,,,,=  =======, ::::::::::777O777777777       III                     
      ,=======,  ======, I::::::::::7777 O777777778    IIZ                      
      ,=======: ,======, M::::::::::I7777  O77777777$7II8                       
      ~,=====,  ======,  M:::::::::::7777M    ~8777787777                       
        ,:=,,  =======,  8:::::::::::77777.       87IM78                        
              ,,,,,,,,  M7M:::::::::~77777M       IIIM                          
             ,======~~ M777+::::::::7777778     ,II7                            
            ,=======, I77777M::::::7777777M ~II8II8                             
            ========: M7777777M:::77777777M877ZIIO7M                            
           ,========  M7777777   877777777777III7777M                           
           ,,~======MZ77M7777,     M777777 ~III77ZM                             
           ===,,,,==I$O$M77777      .77777IIII                                  
     ,,,=??=========,$$M=???????,????,777$II8                                   
  ,,=???=??,==========,,??????,?????===7III:                                    
 ,~??????,?,====================,======III$7O                                   
 ,???????,??,=========,=========,=====III777777M                                
 ,???????,???,=======,==========,======8777M777$$$                              
  ,,,,,,,,,,~, ,=~,,===========:,======,,7Z$ZZ$$M$$                             
                 ~,,~=========,,====~,,   M$$$M$$$M:                            
                       ~,,,,,,,,,,,.        $$$ IM:                             
                                                                   ' 
