#!/bin/sh
#
# Hexley DarwinOS Mascot Copyright 2000 by Jon Hooper. All Rights Reserved.
# Copyright (c) 2007-2008 The PureDarwin Project.
# All rights reserved.
#
# @LICENSE_HEADER_START@
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# @LICENSE_HEADER_END@
#

#
# aladin <aladin@puredarwin.org>
#

#
# This script displays an ascii-art of Hexley mascott 
#

#
# Changelog
#
# 20081209 - License header update - aladin
# 20080925 - Initial release - aladin
#


echo '          N                                                            
         $7                                                            
     ?   N7N                          Z                                
    NN   $77N   7Z~                 ?777                               
  =778  D777$   777N          INNNNNN$77N                              
 N777$  N777ON  $77Z8      7Z7777777777Z87777777$N                     
  N7N8=   Z7    7 87N      $777DZ$OD$77777N77777777D                   
  7Z      878      77N     7777777$MMMND$777Z77777777N                 
 D7N      D7N      N77=    Z777M88OOOOOOOOD77N77777777$                
 N7N      N7N      ?77N    ~77MOO8OOOOOOOOOO$7Z77777777Z               
 87N      N7Z       $7O     7NM~OOOOOOOOOOMOO77N77777777N              
 87N      N77      Z77D      M  OOOOOOMMDOOMOD77Z7777$NO8NNZ7D         
 N77N     N77=     $77D        OOOOOM    :O8OO777777D77777777N         
  777$N   N77N  DD777N     MM ~8OOO,      DOON777777O7777777$          
   O777777777777777O$   NDOOOMMOOOM       DOO8777777N777777D           
     N$7777777778N  :88 OOOOOOOOOO$    MMMOOO77777777DD77Z8            
           $7D       888MND888888OD    MMMOOD77777777777N              
           O7Z        ZM8888888888O    MNOOOD77777777777N              
           N77          O888888M888DOOOOOOOO77777777777N               
           N77+           888888888888888MON777777777NI                
           N77D            ~D8888888888MM8ON777777ND                   
           877N             8$8MNDND+$8888O8777$N                      
           ?77N            Z8$$$$N7788MOOODZ777$                       
          :O77NN           M8$$$$$8MOOD    $7777                       
          MOOMOOOO         NO8888M~OO8$    Z7777N                      
          8OOMZOOOD     MOOO~~~~~~OOOOOO+  D77777O                     
           N877OOOOOMMOOOOO~~~~~~~OOOOOOOO.N777777:                    
           8OO78OOOOOOOOOO~~~~~~~~OOOOOOOOO?DN8N$                      
            N77OOOOOOOOOO$~~~~~~~~OOOOOOOOOOM       Welcome to PureDarwin nano
            877N$OOOOOOON~~~~~~~~~OOO8OOOOOOOM                         
            +77N DOOOOOO~~~~~~~~~~~OOONOOOOOOO8     This is a proof-of-concept
             77D  .D8M8$~~~~~~~~~~~OOOOMOMOOOOM     of a minimal Darwin system
             77Z       ~~~~~~~~~~~~ZOOOOOOOOOO      that can be built from the
             $77      .~~~~~~~~~~~~~OOOOONOOM       DarwinBuild project.
             Z77       ~~~~~~~~~~~~~OOOOOO$         If you would like to help,
             877:      ~~~~~~~~~~~~~?OOOOOO         please join the PureDarwin 
             N77Z      M~~~~~~~~~~~~~OOOOOOO        project.
             N77N     DO=~~~~~~~~~~~IOOOOOOO        http://www.puredarwin.org/
             N77N    DOOO=~~~~~~~~~DOOOOOOOO                           
             Z77D   MOOOOOD~~~~~~=OOOOOOOOON      MDOODMI              
             :77Z   MOOOOOOOD~~~MOOOOOOOOODO MOOOOOOOOOOOO             
              $77.  DOM8OOOOOOOMOOOOOOOOO8OOMOOOOOOOOO8OO7             
              Z778888MMOOOOOOOO8OOOOOOOOONOOOOOOOOOOOON                
              D77N8M8888OOOMD    ~MOOO8OOO     :                       
              N7$OI88NN        M88NMDOODOO                             
                              88M888D888D                              
                                NMO M888 ';

