#!/bin/sh
#
# Copyright (c) 2007-2009 The PureDarwin Project.
# All rights reserved.
#
# @LICENSE_HEADER_START@
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# @LICENSE_HEADER_END@
#

#
# aladin   <aladin@puredarwin.org>
#

#
# PureDarwin install (wrapper) script
#
#	Usage: pd_installer
#
# This script should not be run manually but by launchd via its respective plist.
#
# Based on the "OpenDarwin install script" by kvv
# $Id: rc.cdrom,v 1.30 2005/04/28 20:06:46 kevin Exp $
#
# Based on the "PureDarwin boot installer" (pd_installer_1) by Stuart Crook
#	v1.0 31/03/09 Initial release 

###############################################################################
# GLOBAL VARIABLES AND SETTINGS 
###############################################################################

# Redirecting stdin  (/dev/stdin  -> /dev/fd/0)
exec 0</dev/console
# Redirecting stdout (/dev/stdout -> /dev/fd/1)
exec 1>/dev/console
# Redirecting stderr (/dev/stderr -> /dev/fd/2)
exec 2>/dev/console

# File creation mask
umask 022			# all files created are -rw-r--r--

# Env
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/libexec:/System/Library/CoreServices
export MANPATH=/usr/share/man:/usr/local/man
export EDITOR=/usr/bin/vi
export TERM=xterm-color

# Setting hostname
sysctl -w kern.hostname="PureDarwin.local"

# Populating /dev/fd/ with mount_fdesc
/sbin/mount -t fdesc -o union stdin /dev

# Workaround read-write
#/sbin/mount -uw /

# Find out where this script lives
DIRNAME=$(cd $(dirname $0) && pwd)

###############################################################################
# FUNCTIONS 
###############################################################################

add_user () {
	$DIRNAME/pd_injectuser # e.g., /usr/local/share/puredarwin/scripts/pd_injectuser
}

welcome() {

	clear
	echo
	echo "Welcome to PureDarwin!" # /etc/motd
	echo
	echo " Darwin (c) 1999-2009 Apple, Inc. (opensource.apple.com)"
	echo " Purity (c) 2007-2009 The PureDarwin Project (www.puredarwin.org)"
	echo

	#if [ -f "/Release Notes.txt" ]; then
	#	echo ""
	#	echo "Welcome to the installation of" `grep 'Darwin [0-9.-]*' /Release\ Notes.txt | head -1 | awk '{print $1" "$2}'`
	#	echo ""
	#fi
	#if [ -f "/Important Notice.txt" ]; then
	#	cat "/Important Notice.txt"
	#fi
}

###############################################################################
# INTRO 
###############################################################################

welcome

###############################################################################
# TARGET 
###############################################################################

echo
echo "Enter 's' to drop into a shell."
echo

# Get the device the user wants to install onto.
INSTALLDEV="novalue"
until [[ ${INSTALLDEV} != "" && -b ${INSTALLDEV} ]]
do
	echo "The following devices are available for installation:"
	until [[ ! -z "${FOO}" ]]
	do
		FOO=`$DIRNAME/../setup/pd_setup_files/iofindwholemedia`
	done
	$DIRNAME/../setup/pd_setup_files/iofindwholemedia
	printf "Which device would you like to install PureDarwin onto? "
	read INSTALLDEV

	if [ "${INSTALLDEV}" == "s" ]; then
		# Drop into a shell (resume at exit)
		/bin/sh
	else
		# Check and retrieve the disk device node (e.g., /dev/disk1)
		T_INSTALLDEV="$INSTALLDEV"
		INSTALLDEV=`$DIRNAME/../setup/pd_setup_files/iofindwholemedia ${INSTALLDEV}`

		if [ ! -b "${INSTALLDEV}" ]; then
			echo ""
			echo "${T_INSTALLDEV} doesn't exist, please enter one of the listed devices."
			echo ""
		fi
	fi
done

###############################################################################
# SETUP BASE
###############################################################################

# FIXME add a way to extend or reduce releases (e.g. bootstrap->nano or bootstrap->full)
/usr/local/share/puredarwin/setup/pd_setup $INSTALLDEV PureDarwin

echo "Installation of the base system should now be complete."
echo ""

###############################################################################
# POST CONFIG 
###############################################################################

# Unpopulating /dev 
/sbin/umount /dev

until [ ! : ]
do
	echo "You may: "
	# FIXME adduser will not work if the partition is unmounted
	#echo "1. Add a user to the new system"
	echo "2. Reboot"
	echo "3. Spawn a shell"
	echo -n "Your Choice: "
	read CHOICE
	echo
	case ${CHOICE} in
		#1) add_user 
		#   break;;
		2) reboot
		   break ;;
		3) /bin/sh
		   break ;;
	esac
done


###############################################################################
# REBOOT 
###############################################################################

echo
echo "Installation should now be complete. Press 'enter' to restart"
echo
read RESTART
echo ""
reboot

# bash interactive
#/bin/bash -i 

# zsh interactive
#/bin/zsh -i


