######################################################################
#BEGIN	Machine dependent Makefile fragment for riscv64
######################################################################

CWARNFLAGS   = $(CWARNFLAGS_STD) -Wno-unused-parameter  -Wshorten-64-to-32 -Wimplicit-int-conversion
CXXWARNFLAGS = $(CXXWARNFLAGS_STD) -Wno-unused-parameter -Wno-cast-qual -Wno-shadow  -Wshorten-64-to-32 -Wimplicit-int-conversion

IOHibernateIO.cpo_INCFLAGS += -I$(SRCROOT)/osfmk
IOUnifiedAddressTranslator.cpo_INCFLAGS += -I$(SRCROOT)/osfmk

######################################################################
#END	Machine dependent Makefile fragment for riscv64
######################################################################
