{ stdenv
, lib
, requireFile
, perl
, gperf
, gnused
, darwinCrossToolchain
, nativeLd
, libSystem
, libhubbub
, libwapcaplet
, libparserutils
, targetTriple ? "x86_64-apple-darwin20.4"
}:

let
  deps = [ libwapcaplet libparserutils ];
  sdkTarball = requireFile {
    name = "MacOSX11.3.sdk.tar.xz";
    sha256 = "9adc1373d3879e1973d28ad9f17c9051b02931674a3ec2a2498128989ece2cb1";
    message = ''
      MacOSX11.3.sdk.tar.xz (Apple SDK, proprietary - not fetchable/redistributable)
      is not yet in your Nix store. Register your local copy with:
        nix-store --add-fixed sha256 /path/to/MacOSX11.3.sdk.tar.xz
    '';
  };

  srcs = [
    "src/charset/detect.c"
    "src/parser.c"
    "src/tokeniser/entities.c"
    "src/tokeniser/tokeniser.c"
    "src/treebuilder/after_after_body.c"
    "src/treebuilder/after_after_frameset.c"
    "src/treebuilder/after_body.c"
    "src/treebuilder/after_frameset.c"
    "src/treebuilder/after_head.c"
    "src/treebuilder/before_head.c"
    "src/treebuilder/before_html.c"
    "src/treebuilder/element-type.c"
    "src/treebuilder/generic_rcdata.c"
    "src/treebuilder/in_body.c"
    "src/treebuilder/in_caption.c"
    "src/treebuilder/in_cell.c"
    "src/treebuilder/in_column_group.c"
    "src/treebuilder/in_foreign_content.c"
    "src/treebuilder/in_frameset.c"
    "src/treebuilder/in_head.c"
    "src/treebuilder/in_head_noscript.c"
    "src/treebuilder/initial.c"
    "src/treebuilder/in_row.c"
    "src/treebuilder/in_select.c"
    "src/treebuilder/in_select_in_table.c"
    "src/treebuilder/in_table_body.c"
    "src/treebuilder/in_table.c"
    "src/treebuilder/treebuilder.c"
    "src/utils/errors.c"
    "src/utils/string.c"
  ];
in
stdenv.mkDerivation {
  pname = "puredarwin-libhubbub";
  inherit (libhubbub) version src;

  nativeBuildInputs = [ perl gperf gnused ];

  buildPhase = ''
    runHook preBuild

    mkdir -p sdk
    tar xf ${sdkTarball} -C sdk
    export DARWIN_SDK_ROOT="$PWD/sdk/MacOSX11.3.sdk"

    perl build/make-entities.pl

    gperf --output-file=src/treebuilder/autogenerated-element-type.c.tmp src/treebuilder/element-type.gperf
    sed -e 's/^\(const struct element_type_map\)/static \1/' src/treebuilder/autogenerated-element-type.c.tmp > src/treebuilder/autogenerated-element-type.c

    CC="${darwinCrossToolchain}/bin/${targetTriple}-clang"

    CFLAGS="-isysroot $DARWIN_SDK_ROOT -mmacosx-version-min=11.0 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0 -fno-stack-protector -Iinclude -Isrc -I${libSystem}/usr/include ${lib.concatMapStringsSep " " (dep: "-I${dep}/include") deps}"

    for f in ${lib.concatStringsSep " " srcs}; do
      obj=$(echo "$f" | tr '/' '_').o
      "$CC" $CFLAGS -c "$f" -o "$obj"
    done

    "$CC" -dynamiclib \
      -isysroot "$DARWIN_SDK_ROOT" -mmacosx-version-min=11.0 \
      -fuse-ld=${nativeLd}/bin/ld \
      -nostdlib \
      -L${libSystem}/usr/lib ${lib.concatMapStringsSep " " (dep: "-L${dep}/lib") deps} \
      -Wl,-dylib_file,/usr/lib/system/libdyld.dylib:${libSystem}/usr/lib/system/libdyld.dylib \
      -Wl,-platform_version,macos,11.0,11.5 \
      -install_name /lib/libhubbub.dylib \
      -lwapcaplet -lparserutils -lSystem \
      *.o \
      -o libhubbub.dylib

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p "$out/lib/pkgconfig" "$out/include"
    install -m755 libhubbub.dylib "$out/lib/libhubbub.dylib"
    cp -r include/hubbub "$out/include/hubbub"

    cat > "$out/lib/pkgconfig/libhubbub.pc" <<EOF
prefix=$out
libdir=\''${prefix}/lib
includedir=\''${prefix}/include

Name: libhubbub
Description: HTML parsing library for NetSurf
Version: ${libhubbub.version}
Requires: libparserutils libwapcaplet
Libs: -L\''${libdir} -lhubbub
Cflags: -I\''${includedir}
EOF

    runHook postInstall
  '';

  dontFixup = true;

  meta = with lib; {
    description = "libhubbub (NetSurf HTML5 parsing library), cross-built for PureDarwin";
    platforms = platforms.linux;
  };
}
