{ stdenv
, lib
, requireFile
, darwinCrossToolchain
, nativeLd
, libSystem
, libcxxabiDylib
, src
}:

# Cross-builds Apple's objc4 runtime into /usr/lib/libobjc.A.dylib.
#
# Source: the vendored objc4 study repo at src/Libraries/objc4. The link recipe
# mirrors its objc.xcconfig (product objc.A, -lc++abi, the __objc_data sectalign,
# the order/unexported symbol lists, LIBC_NO_LIBCRASHREPORTERCLIENT).
#
# The C++/exception/unwind symbols objc references via -lc++abi come from our
# libcxxabiDylib (/usr/lib/libc++abi.dylib). Everything else resolves against
# libSystem. dyld here already implements the 3-arg _dyld_objc_notify_register
# ABI objc-os.mm uses, and recognizes __objc_* sections.

let
  sdkTarball = requireFile {
    name = "MacOSX11.3.sdk.tar.xz";
    sha256 = "9adc1373d3879e1973d28ad9f17c9051b02931674a3ec2a2498128989ece2cb1";
    message = ''
      MacOSX11.3.sdk.tar.xz (Apple SDK, proprietary - not fetchable/redistributable)
      is not yet in your Nix store. Register your local copy with:
        nix-store --add-fixed sha256 /path/to/MacOSX11.3.sdk.tar.xz
    '';
  };

  cc = "${darwinCrossToolchain}/bin/x86_64-apple-darwin20.4-clang";
  # All runtime/*.mm are part of libobjc (the -old variants self-gate on the
  # current config). objcdt/objcrt tools and their sources are not included.
  mmSrcs = [
    "hashtable2" "maptable" "NSObject" "objc-accessors" "objc-auto"
    "objc-block-trampolines" "objc-cache" "objc-cache-old" "objc-class"
    "objc-class-old" "objc-errors" "objc-exception" "objc-file" "objc-file-old"
    "objc-initialize" "objc-layout" "objc-loadmethod" "objc-load"
    "objc-lockdebug" "objc-opt" "objc-os" "objc-references" "objc-runtime"
    "objc-runtime-new" "objc-runtime-old" "objc-sel" "objc-sel-old"
    "objc-sel-set" "objc-sync" "objc-typeencoding" "objc-weak" "objc-zalloc"
    "Object" "Protocol"
  ];
  # x86_64 assembly.
  asmSrcs = [
    "Messengers.subproj/objc-msg-x86_64"
    "objc-blocktramps-x86_64"
    "objc-sel-table"
  ];
in
stdenv.mkDerivation {
  pname = "puredarwin-libobjc";
  version = "1";

  inherit src;

  nativeBuildInputs = [ stdenv.cc ];

  buildPhase = ''
    runHook preBuild

    mkdir -p sdk
    tar xf ${sdkTarball} -C sdk
    export DARWIN_SDK_ROOT="$PWD/sdk/MacOSX11.3.sdk"

    O=src/Libraries/objc4
    PRIV=$O/macosx.internal/System/Library/Frameworks/System.framework/Versions/B/PrivateHeaders

    # Build a self-consistent <objc/*.h> include dir from objc4's own headers,
    # so our sources see the headers matching the runtime we compile (not the
    # SDK's copy).
    mkdir -p incdir/objc
    cp -a $O/runtime/*.h incdir/objc/

    # objc-probes.h is normally generated by `dtrace -h` from objc-probes.d.
    # PD has no DTrace, so stub the two probe macros objc-exception.mm uses as
    # no-ops (runtime/ is read-only in the store, so put it on the -I path).
    mkdir -p genhdr
    cat > genhdr/objc-probes.h <<'EOF'
    #ifndef _OBJC_PROBES_H
    #define _OBJC_PROBES_H
    #define OBJC_RUNTIME_OBJC_EXCEPTION_THROW(arg0) do {} while (0)
    #define OBJC_RUNTIME_OBJC_EXCEPTION_RETHROW() do {} while (0)
    #define OBJC_RUNTIME_OBJC_EXCEPTION_THROW_ENABLED() (0)
    #define OBJC_RUNTIME_OBJC_EXCEPTION_RETHROW_ENABLED() (0)
    #endif
    EOF

    # -fno-objc-arc: objc4 runtime is MRC. RTTI/exceptions on (objc-exception,
    # private_typeinfo). Our incdir is ahead of -isysroot so <objc/*> is ours.
    CXXFLAGS="-x objective-c++ -std=gnu++17 -fno-objc-arc -fexceptions \
      -fobjc-exceptions -fPIC -Os -DNDEBUG -DLIBC_NO_LIBCRASHREPORTERCLIENT \
      -D__PUREDARWIN__=1 \
      -Wno-undef-prefix \
      -isysroot $DARWIN_SDK_ROOT \
      -Igenhdr -Iincdir -I$O/runtime -I$PRIV -I${libSystem}/usr/include"

    objs=""
    for s in ${lib.concatStringsSep " " mmSrcs}; do
      ${cc} $CXXFLAGS -c "$O/runtime/$s.mm" -o "$(basename $s).o"
      objs="$objs $(basename $s).o"
    done
    for s in ${lib.concatStringsSep " " asmSrcs}; do
      ${cc} -isysroot "$DARWIN_SDK_ROOT" -I$O/runtime -c "$O/runtime/$s.s" -o "$(basename $s).o"
      objs="$objs $(basename $s).o"
    done

    # Link. Flags mirror objc.xcconfig; -fixup_chains is PD's eager-bind fix.
    ${cc} -isysroot "$DARWIN_SDK_ROOT" -dynamiclib \
      -fuse-ld=${nativeLd}/bin/ld -nostdlib \
      -L${libSystem}/usr/lib -L${libcxxabiDylib}/usr/lib \
      -Wl,-platform_version,macos,11.0,11.5 \
      -Wl,-install_name,/usr/lib/libobjc.A.dylib \
      -Wl,-init,__objc_init \
      -Wl,-sectalign,__DATA,__objc_data,0x1000 \
      -Wl,-order_file,$O/libobjc.order \
      -Wl,-unexported_symbols_list,$O/unexported_symbols \
      -Wl,-fixup_chains \
      -lc++abi -lSystem \
      -o libobjc.A.dylib $objs

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p $out/usr/lib $out/usr/include/objc
    cp libobjc.A.dylib $out/usr/lib/
    ln -s libobjc.A.dylib $out/usr/lib/libobjc.dylib
    cp -a incdir/objc/. $out/usr/include/objc/
    runHook postInstall
  '';

  dontFixup = true;

  meta = with lib; {
    description = "Apple objc4 Objective-C runtime, cross-built as /usr/lib/libobjc.A.dylib";
    platforms = platforms.linux;
  };
}
