#!/bin/sh
#
# Copyright (c) 2007-2009 The PureDarwin Project.
# All rights reserved.
#
# @LICENSE_HEADER_START@
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# @LICENSE_HEADER_END@
#

#
# aladin   <aladin@puredarwin.org>
# probono <probono@puredarwin.org>
#

#
# Hold configuration information needed by other scripts
#

#
# Changelog
#
# 20090326 - Please, see `hg log' or `svn log' from now (Mercurial) - aladin
# 20081219 - Added 9G55 and 9G55pd1 (experimental patched packages) - aladin
# 20081210 - Added 9F33pd1 (experimental patched packages) - aladin
# 20081209 - License header update - aladin
# 20080921 - Added 9F33 version in BINVERSION - aladin
# 20080803 - Added 9E17 and 9D34 versions in BINVERSION - aladin
# 20080606 - Cleaned up - aladin
# 20080528 - Minor updates - aladin
# 20080522 - Cleaned up, removed Darwin 8, PureDarwin starts with Darwin 9
#            releases - probono
# 20080522 - Changed order of buildVersions used, newest first - probono
# 20080305 - Initial release - aladin
#

#
# Darwin release (major version)
#
DARWIN_RELEASE="9"
#DARWIN_RELEASE="10"

#
# PureDarwin release (flavor)
#
PUREDARWIN_RELEASE=""
#PUREDARWIN_RELEASE="nano"

#
# Binaryroot projects list local file
#
BINARYROOTS_LIST_FILE="pd_roots" 
#BINARYROOTS_LIST_FILE="pd_roots.nano"  

#
# Processor architecture / mach-o format
#
ARCH="i386"

#
# Temporary dir which will contain fetched and thinned binaryroots
#
TEMPDIR="pd_tmp"

#
# Where fetched binary roots/drivers are (unpacked/thinned/)repacked (e.g., "./Packages_${ARCH}/")
#
DESTDIR="$TEMPDIR/Packages_D${DARWIN_RELEASE}_${ARCH}" # ...D9_i386 or D10_i386

# Default local binary roots dir
BINARYROOTS_DEFAULT_DIR="$TEMPDIR/Roots"

#
# Additional local directories of binary roots and binary drivers
#
BINARYROOTS_DIR=(
	"$TEMPDIR/BinaryDrivers"
)

#
# Dir of darwinbuild build directories
# FIXME: can sometimes be problematic and create conflicts between dependents and dependencies
#
#DARWINBUILD_DIR="/Users/aladin/PureDarwin/darwinbuild"

#
# Binary roots, drivers and external repository url  (if not found locally)
#
BINARYROOTS_HTTP_PATH=(
	"http://src.macosforge.org/BinaryDrivers"
	"http://src.macosforge.org/Roots"
)

#
# Build versions in Darwin 9 and Darwin 10
#
BINVERSION=(10C540 10B504 10A432 pd 9L30 9J61pd1 9J61 9G55pd1 9G55 9F33pd1 9F33 9E17 9D34 9C31 9B18 9A581)


#
# Default Darwin 9 full options
#

# FIXME: Exclusivity is not always obvious but exists.
# FIXME: add separated version for PureFoundation
# FIXME: add separated version for vanilla and voodoo xnu
# FIXME: add separated version for chameleon
# FIXME: add separated version for VoodooPS2Controller
# etc..

ADD_CHAMELEON="n"		# (default: y) Add Chameleon bootloader?
#ADD_CHAMELEON_THEMES="y"	# (default: y) Add Chameleon bootloader themes?

ADD_MBR_ERASE="y"		# (default: y) Erase existing partition table (instead of updating the MBR)?

ADD_VOODOO_XNU="y"		# (default: y) Add Voodoo Xnu-dev kernel (Voodoo 9.5.0 Kernel Release 1.0 Package (Rev A)?
ADD_PUREFOUNDATION="y"		# (default: y) Add PureFoundation enhancements?

#ADD_VOODOO_XNU_SPEEDSTEP Add xnu-speedstep (Intel SpeedStep driver)? # FIXME
#ADD_VOODOO_POWER Add VoodooPower (Power Management support)? # FIXME
# FIXME Add switch for network support

ADD_VOODOO_PS2CONTROLLER="y"	# (default: y) Add VoodooPS2Controller (VoodooPS2Controller, VoodooPS2Keyboard, VoodooPS2Mouse, VoodooPS2Trackpad)?
ADD_DFE_PS2CONTROLLER="n"	# (default: n) Add David Elliott PS2 support (ACPIPS2Nub, ApplePS2Controller)?

ADD_VMWARE="y"			# (default: y) Add VMware support (VMware-Drivers-OpenSource & VMwareIOFramebuffer.kext)? 

ADD_640x480x32="n"		# (default: n) Add 640x480x32  framebuffer resolution?
ADD_800x600x32="y"		# (default: y) Add 800x600x32  framebuffer resolution? 
ADD_1024x768x32="n"		# (default: n) Add 1024x768x32 framebuffer resolution? 

ADD_LOGIN="y"			# (default: y) Add multiuser login support (pamsessioncreate, pcsc) 
ADD_DEFAULT_USER="y"		# (default: y) Add a default user account: toor (password: toor)?

ADD_X="y"			# (default: n) Add X and other related binaryroots?

ADD_KEYMAP_BELGE="n"		# (default: n) Add Belge keymapping in X?
ADD_KEYMAP_DEUTSCH="n"		# (default: n) Add Deutsch keymapping in X? 
ADD_KEYMAP_FRANCAIS="n"		# (default: n) Add Francais keymapping in X?
ADD_KEYMAP_UK="n"		# (default: n) Add UK keymapping in X?
ADD_KEYMAP_USA="y"		# (default: y) Add USA keymapping in X?

ADD_WMAKER="n"			# (default: n) Add WindowMaker (default window manager)?

ADD_DEBUG="y"			# (default: y) Add debug (verbose launchd and persistent logs in /var/log/syslog)?

ADD_ZSHRC="y"			# (default: y) Add /etc/zshrc? 

ADD_DEVELOPER="y"		# (default: y) Do you want to keep developer headers and libraries?

ADD_MACPORTS="y"		# (default: y) Do you want to add MacPorts (including tcl)

ADD_VMWARE_VMDK="y"		# (default: y) Add VMware VMDK disk image (read-write support)?

ADD_RELEASE_NANO="n"		# (default: n) Build a nano release instead of a full one?

# 
# Darwin 10 full options
#

if [ "$DARWIN_RELEASE" = "10" ]; then
	ADD_VOODOO_XNU="n"	# Not yet released for D10
	ADD_PUREFOUNDATION="n"	# Not yet ready/built for D10
fi

#
# Generic nano options
#

# RESET VAR FOR NANO.. based on above choices, not on default choices
if [ "$PUREDARWIN_RELEASE" = "nano" ]; then
	ADD_RELEASE_NANO="y"	# Switch used in pd_setup
	ADD_PUREFOUNDATION="n"
	ADD_LOGIN="n"	      
	ADD_DEFAULT_USER="n"
	ADD_X="n"
	ADD_DEBUG="n"
	ADD_DEVELOPER="n"
	ADD_MACPORTS="n"
	ADD_VMWARE_VMDK="n"
fi


