// This file is autogenerated for use only by dyld
// DO NOT USE
// DO NOT EDIT


#include <set>
#include <array>
namespace dyld3 {
struct __attribute__((visibility("hidden"))) VersionSetEntry {
    uint32_t set = 0;
    uint32_t macos = 0;
    uint32_t ios = 0;
    uint32_t watchos = 0;
    uint32_t tvos = 0;
    uint32_t bridgeos = 0;
    uint32_t driverkit = 0;
    uint32_t visionos = 0;
    bool operator<(const uint32_t& other) const {
        return set < other;
    }
};

static const std::array<VersionSetEntry, 46> sVersionMap = {{
	{ .set = 0x007db0901, .ios = 0x00050000, .macos = 0x000a0700 },
	{ .set = 0x007dc0901, .ios = 0x00060000, .macos = 0x000a0800 },
	{ .set = 0x007dd0901, .ios = 0x00070000, .macos = 0x000a0900 },
	{ .set = 0x007de0901, .ios = 0x00080000, .macos = 0x000a0a00 },
	{ .set = 0x007df0901, .ios = 0x00090000, .macos = 0x000a0b00, .tvos = 0x00090000, .watchos = 0x00020000 },
	{ .set = 0x007e00901, .ios = 0x000a0000, .macos = 0x000a0c00, .tvos = 0x000a0000, .watchos = 0x00030000 },
	{ .set = 0x007e10901, .bridgeos = 0x00020000, .ios = 0x000b0000, .macos = 0x000a0d00, .tvos = 0x000b0000, .watchos = 0x00040000 },
	{ .set = 0x007e11201, .bridgeos = 0x00020000, .ios = 0x000b0200, .macos = 0x000a0d02, .tvos = 0x000b0200, .watchos = 0x00040200 },
	{ .set = 0x007e20301, .bridgeos = 0x00020000, .ios = 0x000b0300, .macos = 0x000a0d04, .tvos = 0x000b0300, .watchos = 0x00040300 },
	{ .set = 0x007e20901, .bridgeos = 0x00030000, .ios = 0x000c0000, .macos = 0x000a0e00, .tvos = 0x000c0000, .watchos = 0x00050000 },
	{ .set = 0x007e21015, .bridgeos = 0x00030100, .ios = 0x000c0100, .macos = 0x000a0e01, .tvos = 0x000c0100, .watchos = 0x00050100 },
	{ .set = 0x007e30301, .bridgeos = 0x00030400, .ios = 0x000c0200, .macos = 0x000a0e04, .tvos = 0x000c0200, .watchos = 0x00050200 },
	{ .set = 0x007e30601, .bridgeos = 0x00030400, .ios = 0x000c0300, .macos = 0x000a0e05, .tvos = 0x000c0300, .watchos = 0x00050200 },
	{ .set = 0x007e30715, .bridgeos = 0x00030400, .ios = 0x000c0400, .macos = 0x000a0e06, .tvos = 0x000c0400, .watchos = 0x00050300 },
	{ .set = 0x007e30901, .bridgeos = 0x00040000, .driverkit = 0x00130000, .ios = 0x000d0000, .macos = 0x000a0f00, .tvos = 0x000d0000, .watchos = 0x00060000 },
	{ .set = 0x007e30902, .bridgeos = 0x00040000, .driverkit = 0x00130000, .ios = 0x000d0100, .macos = 0x000a0f00, .tvos = 0x000d0000, .watchos = 0x00060000 },
	{ .set = 0x007e31015, .bridgeos = 0x00040100, .driverkit = 0x00130000, .ios = 0x000d0200, .macos = 0x000a0f01, .tvos = 0x000d0200, .watchos = 0x00060100 },
	{ .set = 0x007e31201, .bridgeos = 0x00040100, .driverkit = 0x00130000, .ios = 0x000d0300, .macos = 0x000a0f01, .tvos = 0x000d0300, .watchos = 0x00060100 },
	{ .set = 0x007e40301, .bridgeos = 0x00040100, .driverkit = 0x00130000, .ios = 0x000d0400, .macos = 0x000a0f04, .tvos = 0x000d0400, .watchos = 0x00060200 },
	{ .set = 0x007e40415, .bridgeos = 0x00040100, .driverkit = 0x00130000, .ios = 0x000d0500, .macos = 0x000a0f04, .tvos = 0x000d0400, .watchos = 0x00060200 },
	{ .set = 0x007e40601, .bridgeos = 0x00040100, .driverkit = 0x00130000, .ios = 0x000d0600, .macos = 0x000a0f04, .tvos = 0x000d0400, .watchos = 0x00060200 },
	{ .set = 0x007e40715, .bridgeos = 0x00040100, .driverkit = 0x00130000, .ios = 0x000d0700, .macos = 0x000a0f04, .tvos = 0x000d0400, .watchos = 0x00060200 },
	{ .set = 0x007e40901, .bridgeos = 0x00050000, .driverkit = 0x00140000, .ios = 0x000e0000, .macos = 0x000a1000, .tvos = 0x000e0000, .watchos = 0x00070000 },
	{ .set = 0x007e41015, .bridgeos = 0x00050000, .driverkit = 0x00140000, .ios = 0x000e0200, .macos = 0x000a1000, .tvos = 0x000e0200, .watchos = 0x00070100 },
	{ .set = 0x007e41201, .bridgeos = 0x00050100, .driverkit = 0x00140000, .ios = 0x000e0300, .macos = 0x000b0100, .tvos = 0x000e0300, .watchos = 0x00070200 },
	{ .set = 0x007e50301, .bridgeos = 0x00050300, .driverkit = 0x00140000, .ios = 0x000e0500, .macos = 0x000b0300, .tvos = 0x000e0500, .watchos = 0x00070400 },
	{ .set = 0x007e50901, .bridgeos = 0x00060000, .driverkit = 0x00150000, .ios = 0x000f0000, .macos = 0x000c0000, .tvos = 0x000f0000, .watchos = 0x00080000 },
	{ .set = 0x007e51015, .bridgeos = 0x00060000, .driverkit = 0x00150000, .ios = 0x000f0100, .macos = 0x000c0000, .tvos = 0x000f0100, .watchos = 0x00080100 },
	{ .set = 0x007e51201, .bridgeos = 0x00060200, .driverkit = 0x00150000, .ios = 0x000f0200, .macos = 0x000c0100, .tvos = 0x000f0200, .watchos = 0x00080300 },
	{ .set = 0x007e51215, .bridgeos = 0x00060200, .driverkit = 0x00150000, .ios = 0x000f0300, .macos = 0x000c0200, .tvos = 0x000f0300, .watchos = 0x00080400 },
	{ .set = 0x007e60301, .bridgeos = 0x00060400, .driverkit = 0x00150000, .ios = 0x000f0400, .macos = 0x000c0300, .tvos = 0x000f0400, .watchos = 0x00080500 },
	{ .set = 0x007e6040f, .bridgeos = 0x00060500, .driverkit = 0x00150000, .ios = 0x000f0500, .macos = 0x000c0400, .tvos = 0x000f0500, .watchos = 0x00080600 },
	{ .set = 0x007e60601, .bridgeos = 0x00060600, .driverkit = 0x00150000, .ios = 0x000f0600, .macos = 0x000c0500, .tvos = 0x000f0600, .watchos = 0x00080700 },
	{ .set = 0x007e60901, .bridgeos = 0x00070000, .driverkit = 0x00160000, .ios = 0x00100000, .macos = 0x000d0000, .tvos = 0x00100000, .watchos = 0x00090000 },
	{ .set = 0x007e61015, .bridgeos = 0x00070100, .driverkit = 0x00160000, .ios = 0x00100100, .macos = 0x000d0100, .tvos = 0x00100100, .watchos = 0x00090100 },
	{ .set = 0x007e62100, .bridgeos = 0x00070100, .driverkit = 0x00160000, .ios = 0x00100200, .macos = 0x000d0100, .tvos = 0x00100200, .watchos = 0x00090200 },
	{ .set = 0x007e62200, .bridgeos = 0x00070200, .driverkit = 0x00160000, .ios = 0x00100300, .macos = 0x000d0200, .tvos = 0x00100300, .watchos = 0x00090300 },
	{ .set = 0x007e62300, .bridgeos = 0x00070300, .driverkit = 0x00160400, .ios = 0x00100400, .macos = 0x000d0300, .tvos = 0x00100400, .watchos = 0x00090400 },
	{ .set = 0x007e62400, .bridgeos = 0x00070400, .driverkit = 0x00160500, .ios = 0x00100500, .macos = 0x000d0400, .tvos = 0x00100500, .watchos = 0x00090500 },
	{ .set = 0x007e62500, .bridgeos = 0x00070600, .driverkit = 0x00160600, .ios = 0x00100700, .macos = 0x000d0700, .tvos = 0x00100600, .watchos = 0x00090600 },
	{ .set = 0x007e70901, .bridgeos = 0x00080000, .driverkit = 0x00170000, .ios = 0x00110000, .macos = 0x000e0000, .tvos = 0x00110000, .watchos = 0x000a0000 },
	{ .set = 0x007e70c01, .bridgeos = 0x00080100, .driverkit = 0x00170100, .ios = 0x00110100, .macos = 0x000e0100, .tvos = 0x00110100, .visionos = 0x00010000, .watchos = 0x000a0100 },
	{ .set = 0x007e70d01, .bridgeos = 0x00080200, .driverkit = 0x00170200, .ios = 0x00110200, .macos = 0x000e0200, .tvos = 0x00110200, .visionos = 0x00010000, .watchos = 0x000a0200 },
	{ .set = 0x007e70e01, .bridgeos = 0x00080300, .driverkit = 0x00170300, .ios = 0x00110300, .macos = 0x000e0300, .tvos = 0x00110300, .visionos = 0x00010000, .watchos = 0x000a0300 },
	{ .set = 0x007e80901, .bridgeos = 0x00080300, .driverkit = 0x00170300, .ios = 0x00110300, .macos = 0x000f0000, .tvos = 0x00110300, .visionos = 0x00010000, .watchos = 0x000a0300 },
	{ .set = 0x007e90901, .bridgeos = 0x00080300, .driverkit = 0x00170300, .ios = 0x00110300, .macos = 0x001a0000, .tvos = 0x00110300, .visionos = 0x00010000, .watchos = 0x000a0300 }
}};
};

