######################################################################
#BEGIN	Machine dependent Makefile fragment for riscv64
######################################################################

CWARNFLAGS   = $(CWARNFLAGS_STD) -Wshorten-64-to-32 -Wimplicit-int-conversion
CXXWARNFLAGS = $(CXXWARNFLAGS_STD) -Wshorten-64-to-32 -Wimplicit-int-conversion

OSSymbol.cpo_INCFLAGS += -I$(SRCROOT)/osfmk

######################################################################
#END	Machine dependent Makefile fragment for riscv64
######################################################################
